// 브릭셀 모듈 데이터 (120종+)
const brixelModules = [

    // ===== 세트 (Set) =====
    { name: 'rich shild set', nameKr: '리치실드세트', image: 'images/6_color_touch_sensor.jpg', category: 'set' },
    { name: 'mega super rich board set', nameKr: '메가 슈퍼리치보드 세트', image: 'images/7_color_touch_sensor.jpg', category: 'set' },
    { name: 'arduino gorillacell basic set', nameKr: '고릴라셀 기본 세트', image: 'images/8_color_touch_sensor.jpg', category: 'set' },
    { name: 'mabit brixel basic set', nameKr: '마빗 브릭셀 기본 세트', image: 'images/9_color_touch_sensor.jpg', category: 'set' },
    { name: 'arduino brixel ai car set', nameKr: '브릭셀 AI자동차 세트', image: 'images/temp_sensor.jpg', category: 'set' },
    { name: 'mabit brixel ai car set ', nameKr: '마빗 브릭셀 AI자동차 세트', image: 'images/humidity_sensor.jpg', category: 'set' },
    { name: 'esp super rich board set', nameKr: 'ESP 슈퍼리치보드 세트', image: 'images/dht11.jpg', category: 'set' },
    { name: 'DHT22', nameKr: 'DHT22 온습도', image: 'images/dht22.jpg', category: 'set' },


    // ===== 센서 (Sensor) =====
    { name: '6 Color Touch Sensor', nameKr: '6 컬러 터치 센서', image: 'images/6_color_touch_sensor.jpg', category: 'sensor' },
    { name: '7 Color Touch Sensor', nameKr: '7 컬러 터치 센서', image: 'images/7_color_touch_sensor.jpg', category: 'sensor' },
    { name: '8 Color Touch Sensor', nameKr: '8 컬러 터치 센서', image: 'images/8_color_touch_sensor.jpg', category: 'sensor' },
    { name: '9 Color Touch Sensor', nameKr: '9 컬러 터치 센서', image: 'images/9_color_touch_sensor.jpg', category: 'sensor' },
    { name: 'Temperature Sensor', nameKr: '온도 센서', image: 'images/temp_sensor.jpg', category: 'sensor' },
    { name: 'Humidity Sensor', nameKr: '습도 센서', image: 'images/humidity_sensor.jpg', category: 'sensor' },
    { name: 'DHT11', nameKr: 'DHT11 온습도', image: 'images/dht11.jpg', category: 'sensor' },
    { name: 'DHT22', nameKr: 'DHT22 온습도', image: 'images/dht22.jpg', category: 'sensor' },
    { name: 'Ultrasonic Sensor', nameKr: '초음파 센서', image: 'images/ultrasonic.jpg', category: 'sensor' },
    { name: 'PIR Sensor', nameKr: 'PIR 인체감지', image: 'images/pir_sensor.jpg', category: 'sensor' },
    { name: 'Light Sensor', nameKr: '조도 센서', image: 'images/light_sensor.jpg', category: 'sensor' },
    { name: 'Sound Sensor', nameKr: '소리 센서', image: 'images/sound_sensor.jpg', category: 'sensor' },
    { name: 'Vibration Sensor', nameKr: '진동 센서', image: 'images/vibration_sensor.jpg', category: 'sensor' },
    { name: 'Tilt Sensor', nameKr: '기울기 센서', image: 'images/tilt_sensor.jpg', category: 'sensor' },
    { name: 'Flame Sensor', nameKr: '불꽃 센서', image: 'images/flame_sensor.jpg', category: 'sensor' },
    { name: 'Gas Sensor', nameKr: '가스 센서', image: 'images/gas_sensor.jpg', category: 'sensor' },
    { name: 'Smoke Sensor', nameKr: '연기 센서', image: 'images/smoke_sensor.jpg', category: 'sensor' },
    { name: 'Water Level Sensor', nameKr: '수위 센서', image: 'images/water_level.jpg', category: 'sensor' },
    { name: 'Soil Moisture', nameKr: '토양 습도', image: 'images/soil_moisture.jpg', category: 'sensor' },
    { name: 'Rain Sensor', nameKr: '빗물 센서', image: 'images/rain_sensor.jpg', category: 'sensor' },
    { name: 'IR Sensor', nameKr: '적외선 센서', image: 'images/ir_sensor.jpg', category: 'sensor' },
    { name: 'Line Tracking', nameKr: '라인 트래킹', image: 'images/line_tracking.jpg', category: 'sensor' },
    { name: 'Color Sensor', nameKr: '컬러 센서', image: 'images/color_sensor.jpg', category: 'sensor' },
    { name: 'Gesture Sensor', nameKr: '제스처 센서', image: 'images/gesture_sensor.jpg', category: 'sensor' },
    { name: 'Hall Sensor', nameKr: '홀 센서', image: 'images/hall_sensor.jpg', category: 'sensor' },
    { name: 'Magnetic Sensor', nameKr: '자기 센서', image: 'images/magnetic_sensor.jpg', category: 'sensor' },
    { name: 'Pressure Sensor', nameKr: '압력 센서', image: 'images/pressure_sensor.jpg', category: 'sensor' },
    { name: 'Load Cell', nameKr: '로드셀', image: 'images/load_cell.jpg', category: 'sensor' },
    { name: 'Current Sensor', nameKr: '전류 센서', image: 'images/current_sensor.jpg', category: 'sensor' },
    { name: 'Voltage Sensor', nameKr: '전압 센서', image: 'images/voltage_sensor.jpg', category: 'sensor' },
    { name: 'Weight Sensor', nameKr: '무게 센서', image: 'images/weight_sensor.jpg', category: 'sensor' },
    { name: 'Flow Sensor', nameKr: '유량 센서', image: 'images/flow_sensor.jpg', category: 'sensor' },
    { name: 'pH Sensor', nameKr: 'pH 센서', image: 'images/ph_sensor.jpg', category: 'sensor' },
    { name: 'Turbidity Sensor', nameKr: '탁도 센서', image: 'images/turbidity_sensor.jpg', category: 'sensor' },
    { name: 'Gyroscope', nameKr: '자이로스코프', image: 'images/gyroscope.jpg', category: 'sensor' },
    { name: 'Accelerometer', nameKr: '가속도계', image: 'images/accelerometer.jpg', category: 'sensor' },
    { name: 'Compass', nameKr: '나침반', image: 'images/compass.jpg', category: 'sensor' },
    { name: 'IMU Sensor', nameKr: 'IMU 센서', image: 'images/imu_sensor.jpg', category: 'sensor' },
    { name: 'Barometer', nameKr: '기압계', image: 'images/barometer.jpg', category: 'sensor' },
    { name: 'Altimeter', nameKr: '고도계', image: 'images/altimeter.jpg', category: 'sensor' },
    { name: 'UV Sensor', nameKr: 'UV 센서', image: 'images/uv_sensor.jpg', category: 'sensor' },
    { name: 'Dust Sensor', nameKr: '먼지 센서', image: 'images/dust_sensor.jpg', category: 'sensor' },
    { name: 'CO2 Sensor', nameKr: 'CO2 센서', image: 'images/co2_sensor.jpg', category: 'sensor' },
    { name: 'Alcohol Sensor', nameKr: '알코올 센서', image: 'images/alcohol_sensor.jpg', category: 'sensor' },
    { name: 'Heart Rate Sensor', nameKr: '심박 센서', image: 'images/heart_rate.jpg', category: 'sensor' },
    { name: 'Fingerprint Sensor', nameKr: '지문 센서', image: 'images/fingerprint.jpg', category: 'sensor' },
    { name: 'EMG Sensor', nameKr: 'EMG 센서', image: 'images/emg_sensor.jpg', category: 'sensor' },
    { name: 'ECG Sensor', nameKr: 'ECG 센서', image: 'images/ecg_sensor.jpg', category: 'sensor' },
    
    // ===== 디스플레이 (Display) =====
    { name: '7 7-Segment', nameKr: '7 7-세그먼트', image: 'images/7_7segment.jpg', category: 'display' },
    { name: 'OLED Display', nameKr: 'OLED 디스플레이', image: 'images/oled_display.jpg', category: 'display' },
    { name: 'LCD 16x2', nameKr: 'LCD 16x2', image: 'images/lcd_16x2.jpg', category: 'display' },
    { name: 'LCD 20x4', nameKr: 'LCD 20x4', image: 'images/lcd_20x4.jpg', category: 'display' },
    { name: 'Dot Matrix 8x8', nameKr: '도트 매트릭스 8x8', image: 'images/dot_matrix_8x8.jpg', category: 'display' },
    { name: 'Dot Matrix 16x16', nameKr: '도트 매트릭스 16x16', image: 'images/dot_matrix_16x16.jpg', category: 'display' },
    { name: 'TFT Display', nameKr: 'TFT 디스플레이', image: 'images/tft_display.jpg', category: 'display' },
    { name: 'E-Paper Display', nameKr: '전자잉크 디스플레이', image: 'images/epaper_display.jpg', category: 'display' },
    { name: '4-Digit Display', nameKr: '4자리 디스플레이', image: 'images/4digit_display.jpg', category: 'display' },
    { name: 'LED Bar Graph', nameKr: 'LED 바 그래프', image: 'images/led_bar_graph.jpg', category: 'display' },
    
    // ===== 출력 (Output) =====
    { name: '8 RGB LED', nameKr: '8 RGB LED', image: 'images/8_rgb_led.jpg', category: 'output' },
    { name: 'LED Red', nameKr: 'LED 빨강', image: 'images/led_red.jpg', category: 'output' },
    { name: 'LED Yellow', nameKr: 'LED 노랑', image: 'images/led_yellow.jpg', category: 'output' },
    { name: 'LED Green', nameKr: 'LED 초록', image: 'images/led_green.jpg', category: 'output' },
    { name: 'LED Blue', nameKr: 'LED 파랑', image: 'images/led_blue.jpg', category: 'output' },
    { name: 'LED White', nameKr: 'LED 흰색', image: 'images/led_white.jpg', category: 'output' },
    { name: 'NeoPixel', nameKr: '네오픽셀', image: 'images/neopixel.jpg', category: 'output' },
    { name: 'LED Strip', nameKr: 'LED 스트립', image: 'images/led_strip.jpg', category: 'output' },
    { name: '6 M_Buzzer', nameKr: '6 M_버저', image: 'images/6_m_buzzer.jpg', category: 'output' },
    { name: 'Passive Buzzer', nameKr: '패시브 버저', image: 'images/passive_buzzer.jpg', category: 'output' },
    { name: 'Active Buzzer', nameKr: '액티브 버저', image: 'images/active_buzzer.jpg', category: 'output' },
    { name: 'Speaker Module', nameKr: '스피커 모듈', image: 'images/speaker_module.jpg', category: 'output' },
    { name: 'MP3 Player', nameKr: 'MP3 플레이어', image: 'images/mp3_player.jpg', category: 'output' },
    { name: 'Relay Module', nameKr: '릴레이 모듈', image: 'images/relay_module.jpg', category: 'output' },
    { name: 'Solenoid', nameKr: '솔레노이드', image: 'images/solenoid.jpg', category: 'output' },
    { name: 'Laser Module', nameKr: '레이저 모듈', image: 'images/laser_module.jpg', category: 'output' },
    { name: 'Fan Module', nameKr: '팬 모듈', image: 'images/fan_module.jpg', category: 'output' },
    { name: 'Vibration Motor', nameKr: '진동 모터', image: 'images/vibration_motor.jpg', category: 'output' },
    
    // ===== 모터 (Motor) =====
    { name: 'Servo Motor', nameKr: '서보 모터', image: 'images/servo_motor.jpg', category: 'motor' },
    { name: 'DC Motor', nameKr: 'DC 모터', image: 'images/dc_motor.jpg', category: 'motor' },
    { name: 'Stepper Motor', nameKr: '스텝 모터', image: 'images/stepper_motor.jpg', category: 'motor' },
    { name: 'Motor Driver L298N', nameKr: '모터 드라이버 L298N', image: 'images/motor_driver_l298n.jpg', category: 'motor' },
    { name: 'Motor Driver L293D', nameKr: '모터 드라이버 L293D', image: 'images/motor_driver_l293d.jpg', category: 'motor' },
    { name: 'Linear Actuator', nameKr: '리니어 액추에이터', image: 'images/linear_actuator.jpg', category: 'motor' },
    { name: 'Gear Motor', nameKr: '기어 모터', image: 'images/gear_motor.jpg', category: 'motor' },
    { name: 'Servo Controller', nameKr: '서보 컨트롤러', image: 'images/servo_controller.jpg', category: 'motor' },
    { name: 'Motor Shield', nameKr: '모터 실드', image: 'images/motor_shield.jpg', category: 'motor' },
    { name: 'Encoder Motor', nameKr: '엔코더 모터', image: 'images/encoder_motor.jpg', category: 'motor' },
    
    // ===== 통신 (Communication) =====
    { name: '6_Bluetooth', nameKr: '6_블루투스', image: 'images/6_bluetooth.jpg', category: 'communication' },
    { name: '7_Bluetooth4', nameKr: '7_블루투스4', image: 'images/7_bluetooth4.jpg', category: 'communication' },
    { name: '8_GPS', nameKr: '8_GPS', image: 'images/8_gps.jpg', category: 'communication' },
    { name: 'WiFi Module ESP8266', nameKr: 'WiFi 모듈 ESP8266', image: 'images/wifi_esp8266.jpg', category: 'communication' },
    { name: 'WiFi Module ESP32', nameKr: 'WiFi 모듈 ESP32', image: 'images/wifi_esp32.jpg', category: 'communication' },
    { name: 'RF433 Module', nameKr: 'RF433 모듈', image: 'images/rf433_module.jpg', category: 'communication' },
    { name: 'NFC Module', nameKr: 'NFC 모듈', image: 'images/nfc_module.jpg', category: 'communication' },
    { name: 'RFID Reader', nameKr: 'RFID 리더', image: 'images/rfid_reader.jpg', category: 'communication' },
    { name: 'Zigbee Module', nameKr: 'Zigbee 모듈', image: 'images/zigbee_module.jpg', category: 'communication' },
    { name: 'LoRa Module', nameKr: 'LoRa 모듈', image: 'images/lora_module.jpg', category: 'communication' },
    { name: 'GSM Module', nameKr: 'GSM 모듈', image: 'images/gsm_module.jpg', category: 'communication' },
    { name: 'Ethernet Module', nameKr: '이더넷 모듈', image: 'images/ethernet_module.jpg', category: 'communication' },
    { name: 'CAN Bus Module', nameKr: 'CAN 버스 모듈', image: 'images/can_bus.jpg', category: 'communication' },
    { name: 'RS485 Module', nameKr: 'RS485 모듈', image: 'images/rs485_module.jpg', category: 'communication' },
    
    // ===== 보드 (Board) =====
    { name: 'Arduino UNO', nameKr: '아두이노 우노', image: 'images/arduino_uno.jpg', category: 'board' },
    { name: 'Arduino Nano', nameKr: '아두이노 나노', image: 'images/arduino_nano.jpg', category: 'board' },
    { name: 'Arduino Mega', nameKr: '아두이노 메가', image: 'images/arduino_mega.jpg', category: 'board' },
    { name: 'Arduino Leonardo', nameKr: '아두이노 레오나르도', image: 'images/arduino_leonardo.jpg', category: 'board' },
    { name: 'Arduino Micro', nameKr: '아두이노 마이크로', image: 'images/arduino_micro.jpg', category: 'board' },
    { name: 'Arduino Due', nameKr: '아두이노 듀', image: 'images/arduino_due.jpg', category: 'board' },
    { name: 'Raspberry Pi', nameKr: '라즈베리파이', image: 'images/raspberry_pi.jpg', category: 'board' },
    { name: 'Raspberry Pi Pico', nameKr: '라즈베리파이 피코', image: 'images/rpi_pico.jpg', category: 'board' },
    { name: 'ESP32 Board', nameKr: 'ESP32 보드', image: 'images/esp32_board.jpg', category: 'board' },
    { name: 'ESP8266 Board', nameKr: 'ESP8266 보드', image: 'images/esp8266_board.jpg', category: 'board' },
    { name: 'Micro:bit', nameKr: '마이크로비트', image: 'images/microbit.jpg', category: 'board' },
    { name: 'STM32 Board', nameKr: 'STM32 보드', image: 'images/stm32_board.jpg', category: 'board' },
    { name: 'Teensy Board', nameKr: 'Teensy 보드', image: 'images/teensy_board.jpg', category: 'board' },
    
    // ===== 실드 (Shield) =====
    { name: 'Proto Shield', nameKr: '프로토 실드', image: 'images/proto_shield.jpg', category: 'shield' },
    { name: 'Ethernet Shield', nameKr: '이더넷 실드', image: 'images/ethernet_shield.jpg', category: 'shield' },
    { name: 'WiFi Shield', nameKr: 'WiFi 실드', image: 'images/wifi_shield.jpg', category: 'shield' },
    { name: 'Motor Shield', nameKr: '모터 실드', image: 'images/motor_shield.jpg', category: 'shield' },
    { name: 'LCD Shield', nameKr: 'LCD 실드', image: 'images/lcd_shield.jpg', category: 'shield' },
    { name: 'Sensor Shield', nameKr: '센서 실드', image: 'images/sensor_shield.jpg', category: 'shield' },
    { name: 'SD Card Shield', nameKr: 'SD 카드 실드', image: 'images/sd_card_shield.jpg', category: 'shield' },
    { name: 'GPS Shield', nameKr: 'GPS 실드', image: 'images/gps_shield.jpg', category: 'shield' },
    { name: 'CNC Shield', nameKr: 'CNC 실드', image: 'images/cnc_shield.jpg', category: 'shield' },
    { name: 'Relay Shield', nameKr: '릴레이 실드', image: 'images/relay_shield.jpg', category: 'shield' },
    { name: 'Joystick Shield', nameKr: '조이스틱 실드', image: 'images/joystick_shield.jpg', category: 'shield' },
    { name: 'Data Logger Shield', nameKr: '데이터로거 실드', image: 'images/datalogger_shield.jpg', category: 'shield' },
    
    // ===== 케이블 (Cable) =====
    { name: 'Jumper Wires M-M', nameKr: '점퍼선 M-M', image: 'images/jumper_mm.jpg', category: 'cable' },
    { name: 'Jumper Wires M-F', nameKr: '점퍼선 M-F', image: 'images/jumper_mf.jpg', category: 'cable' },
    { name: 'Jumper Wires F-F', nameKr: '점퍼선 F-F', image: 'images/jumper_ff.jpg', category: 'cable' },
    { name: 'USB Cable A-B', nameKr: 'USB 케이블 A-B', image: 'images/usb_cable_ab.jpg', category: 'cable' },
    { name: 'USB Cable Micro', nameKr: 'USB 마이크로 케이블', image: 'images/usb_cable_micro.jpg', category: 'cable' },
    { name: 'USB Cable Type-C', nameKr: 'USB Type-C 케이블', image: 'images/usb_cable_typec.jpg', category: 'cable' },
    { name: 'HDMI Cable', nameKr: 'HDMI 케이블', image: 'images/hdmi_cable.jpg', category: 'cable' },
    { name: 'Grove Cable', nameKr: 'Grove 케이블', image: 'images/grove_cable.jpg', category: 'cable' },
    { name: 'Ribbon Cable', nameKr: '리본 케이블', image: 'images/ribbon_cable.jpg', category: 'cable' },
    { name: 'Crocodile Clips', nameKr: '악어클립', image: 'images/crocodile_clips.jpg', category: 'cable' },
    { name: 'JST Connector', nameKr: 'JST 커넥터', image: 'images/jst_connector.jpg', category: 'cable' },
    { name: 'Pin Header', nameKr: '핀 헤더', image: 'images/pin_header.jpg', category: 'cable' },
    { name: 'Terminal Block', nameKr: '터미널 블록', image: 'images/terminal_block.jpg', category: 'cable' },
    
    // ===== 유틸 (Utility) =====
    { name: 'Breadboard', nameKr: '브레드보드', image: 'images/breadboard.jpg', category: 'utility' },
    { name: 'Power Supply', nameKr: '전원 공급기', image: 'images/power_supply.jpg', category: 'utility' },
    { name: 'Battery Holder', nameKr: '배터리 홀더', image: 'images/battery_holder.jpg', category: 'utility' },
    { name: 'Solar Panel', nameKr: '태양광 패널', image: 'images/solar_panel.jpg', category: 'utility' },
    { name: 'Voltage Regulator', nameKr: '전압 레귤레이터', image: 'images/voltage_regulator.jpg', category: 'utility' },
    { name: 'Buck Converter', nameKr: '벅 컨버터', image: 'images/buck_converter.jpg', category: 'utility' },
    { name: 'Boost Converter', nameKr: '부스트 컨버터', image: 'images/boost_converter.jpg', category: 'utility' },
    { name: 'Power Bank', nameKr: '파워 뱅크', image: 'images/power_bank.jpg', category: 'utility' },
    { name: 'RTC Module', nameKr: 'RTC 모듈', image: 'images/rtc_module.jpg', category: 'utility' },
    { name: 'SD Card Module', nameKr: 'SD 카드 모듈', image: 'images/sd_card_module.jpg', category: 'utility' },
    { name: 'EEPROM', nameKr: 'EEPROM', image: 'images/eeprom.jpg', category: 'utility' },
    { name: 'Level Shifter', nameKr: '레벨 시프터', image: 'images/level_shifter.jpg', category: 'utility' },
    { name: 'Multiplexer', nameKr: '멀티플렉서', image: 'images/multiplexer.jpg', category: 'utility' },
    { name: 'GPIO Expander', nameKr: 'GPIO 확장기', image: 'images/gpio_expander.jpg', category: 'utility' },
    { name: 'Heat Sink', nameKr: '방열판', image: 'images/heat_sink.jpg', category: 'utility' },
    { name: 'Button', nameKr: '버튼', image: 'images/button.jpg', category: 'utility' },
    { name: 'Push Button', nameKr: '푸시 버튼', image: 'images/push_button.jpg', category: 'utility' },
    { name: 'Toggle Switch', nameKr: '토글 스위치', image: 'images/toggle_switch.jpg', category: 'utility' },
    { name: 'Rotary Encoder', nameKr: '로터리 인코더', image: 'images/rotary_encoder.jpg', category: 'utility' },
    { name: 'Joystick', nameKr: '조이스틱', image: 'images/joystick.jpg', category: 'utility' },
    { name: 'Keypad 3x4', nameKr: '키패드 3x4', image: 'images/keypad_3x4.jpg', category: 'utility' },
    { name: 'Keypad 4x4', nameKr: '키패드 4x4', image: 'images/keypad_4x4.jpg', category: 'utility' },
    { name: 'Potentiometer', nameKr: '가변저항', image: 'images/potentiometer.jpg', category: 'utility' },
    { name: 'Slide Potentiometer', nameKr: '슬라이드 가변저항', image: 'images/slide_pot.jpg', category: 'utility' },
    { name: 'Camera Module', nameKr: '카메라 모듈', image: 'images/camera_module.jpg', category: 'utility' },
    { name: 'Voice Recognition', nameKr: '음성 인식', image: 'images/voice_recognition.jpg', category: 'utility' },
    { name: 'Barcode Scanner', nameKr: '바코드 스캐너', image: 'images/barcode_scanner.jpg', category: 'utility' },
    { name: 'Peltier Module', nameKr: '펠티어 모듈', image: 'images/peltier_module.jpg', category: 'utility' },
    { name: 'Resistor Kit', nameKr: '저항 키트', image: 'images/resistor_kit.jpg', category: 'utility' },
    { name: 'Capacitor Kit', nameKr: '커패시터 키트', image: 'images/capacitor_kit.jpg', category: 'utility' },
    { name: 'LED Kit', nameKr: 'LED 키트', image: 'images/led_kit.jpg', category: 'utility' },
    { name: 'Sensor Kit', nameKr: '센서 키트', image: 'images/sensor_kit.jpg', category: 'utility' },
    { name: 'Tool Kit', nameKr: '도구 키트', image: 'images/tool_kit.jpg', category: 'utility' }
];

// 모듈 데이터 export (다른 스크립트에서 사용 가능)
if (typeof module !== 'undefined' && module.exports) {
    module.exports = brixelModules;
}